---
Packaging:
  pomVersion: <%= SknUtils::VERSION %>
  isTest: false
  isDevelopment: true
  isStaging: false
  isProduction: false
  configName: development
  short_name: skn

# Create a EnvStringHandler to support: SknSettings.env.development?
# Yes, its YAML trick
env: !ruby/string:SknUtils::EnvStringHandler <%= ENV['RACK_ENV'] %>
root: !ruby/string:SknUtils::EnvStringHandler <%= Dir.pwd %>

